### ISSUE TITLE
Remove jsdom dependency

### ISSUE THREAD

**Issue by maxsnew** [maxsnew/IO#12]
Just copy this from Lazlo: https://github.com/elm-lang/core/blob/master/tests/elm-io-ports.js

**Comment by lowdesertpunk** [comment]
If jsdom gets removed what will happen with elm-lang/elm-repl#48?

**Comment by maxsnew** [comment]
Basically you wouldn't be able to use things like elm-html or `Element` in your IO scripts. If you need that we could probably pass a flag to include jsdom, I just figured no one would use those anyway since you're not running on the browser anyway.

The other thing that this changes is that when the elm runtime changes, `IO` might break, but since the elm stdlib is now tested using `IO` we should detect immediately when that's happened.

**Comment by maxsnew** [comment]
Fixed in https://github.com/maxsnew/IO/commit/48154c96844fcdb638de9497cc6403d7bd73d186

**Comment by lowdesertpunk** [comment]
i was thinking about testing views without needing a browser or some other functional testing framework. although this is probably belongs to `Elm-Test` and not `IO`. `IO` could provide some way through clients could plug-in their own functionality.

**Comment by maxsnew** [comment]
I could see how that would be useful, but I don't really need to do that so I won't bother, but if you implement it I would be open to merging it in.

**Comment by lowdesertpunk** [comment]
ok, will think about it
